In [1]:
# Load the Drive helper and mount
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Lesson 30 - Pytorch tensors and Numpy

- Numpy is a scientific computing library
- Pytorch can interact with numpy
- If we have data in Numpy we may want it in Pytorch tensor
- `torch.from_numpy()` takes in an ndarray and converts it into PyTorch tensor
- `torch.Tensor.numpy()` converts tensor to numpy ndarray

## torch.from_numpy()

In [3]:
array = np.arange(1., 8.)
array

array([1., 2., 3., 4., 5., 6., 7.])

In [4]:
tensor = torch.from_numpy(array)
tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

## torch.Tensor.numpy()

In [5]:
tensor2 = torch.ones(7)
tensor2

tensor([1., 1., 1., 1., 1., 1., 1.])

In [6]:
torch.Tensor.numpy(tensor2)

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)

# Lesson 31 - Reproducability - seeds

- NN in short `start with random numbers -> tensor operations -> try to make better (again and again and again)`
- When making reproducible / make sure the experiment always starts with the same random numbers we introduce seeds
- torch.rand() does not have seed method, we'll have to use `torch.manual_seed()` everytime

In [7]:
random_seed = 42

torch.manual_seed(random_seed)
torch.rand(3, 4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [8]:
torch.manual_seed(random_seed)
torch.rand(3, 4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])