In [1]:
# Load the Drive helper and mount
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Lesson 18 - Creating a Range of Tensors and Tensor-like

- `torch.arange()` create a tensor containing a sequence of values evenly spaced within a specified range.

In [3]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
torch.arange(start=2,end=5)

tensor([2, 3, 4])

In [8]:
torch.arange(start=5, end=50, step =7)

tensor([ 5, 12, 19, 26, 33, 40, 47])

## Creating Tensors like

- Replicate the shape of the tensor, but dont want to explicitly tell what shape should be

In [9]:
zero_to_10 = torch.arange(0,11)
zero_to_10

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
ten_zeros = torch.zeros_like(zero_to_10)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])