In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from torch import nn

# Lesson 43 - Checking contents of the model
- We can check what's inside the model using `.parameters()`

## From the previous video

In [6]:
# Creating a linear regression model class

class LinearRegressionModel(nn.Module):
  # Creating constructor
  def __init__(self):
    super().__init__()
    self.weights = nn.Parameter(torch.randn(1, # <- start with random weights (this will get adjusted as the model learns)
                                            dtype = torch.float), # <- PyTorch loves float32 by default
                                            requires_grad = True) # by default is also true
    self.bias = nn.Parameter(torch.randn(1,
                                         dtype = torch.float), # <- PyTorch loves float32 by default
                                          requires_grad = True)

    # Forward method to define the computation in the model
  def forward(self, x: torch.Tensor) -> torch.Tensor:
    return self.weights * x + self.bias

## Creating the instance of the Model

- This is the subclass of the nn.Module

In [13]:
torch.manual_seed(88) # we'll get the same initial values when using seed

model_0 = LinearRegressionModel() # calling the class

In [14]:
list(model_0.parameters())

[Parameter containing:
 tensor([0.5734], requires_grad=True),
 Parameter containing:
 tensor([1.3148], requires_grad=True)]

In [16]:
# Another method
model_0.state_dict()

OrderedDict([('weights', tensor([0.5734])), ('bias', tensor([1.3148]))])

In [15]:
torch.manual_seed(88)
torch.randn(1)

tensor([0.5734])