In [1]:
# Load the Drive helper and mount
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Lesson 32 - Running Tensors and PyTorch Objects on GPUs

1. Getting a GPU - change runtime type

In [2]:
#check gpu
!nvidia-smi

Sun Oct 22 06:22:44 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
# Check for GPU access with PyTorch
torch.cuda.is_available()

True

## Setting up Device Agnostic code

In [5]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

## Counting number of GPUs

In [6]:
torch.cuda.device_count()

1

# Lesson 33 - Putting Tensors and Models in the GPU

Using a gpu results in faster computations

In [7]:
# Creating a tensor - default is on CPU

tensor1 = torch.tensor([1, 2, 3], device = 'cpu') # by default device is cpu

tensor1, tensor1.device

(tensor([1, 2, 3]), device(type='cpu'))

## Shifting the current tensor to GPU

In [8]:
device

'cuda'

In [9]:
tensor2 = tensor1.to(device)
tensor2, tensor2.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

## Converting a Tensor to Numpy

- `Numpy` only works on cpu

In [10]:
# Transforming tensor to numpy
tensor2.numpy()

TypeError: ignored

1. Need to change device first as cpu
2. Convert it to Numpy

In [12]:
tensor3 = tensor2.cpu().numpy()
tensor3

array([1, 2, 3])