In [ ]:
# Load the Drive helper and mount
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Lesson 27+28 - Reshaping, Stacking, Squeezing, and Unsqueezing

1. `Reshaping:` Reshapes an input tensor to a defined shape
2. `View:` Return a view of an input tensor of certain shape but keep the same memory as the original tensor. (Similar to Rehape but keeps same memory of original tensor)
3. `Stacking:` Combine multiple tensors on top of each other
  - Horizontal
  - Vertical
4. `Squeeze:` Removes all `1` dimensions from a tensor
5. `Unsqueeze:` Adds a `1` dimension to a tensor
6. `Permute:` Return a view of the input with dimensions permuted (swapped) in a certain way

**Main point of all the above methods is to manipulate our tensors to change their shape or dimension**

In [ ]:
x = torch.arange(1., 10., step=1.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

## 1. Reshaping

`The new Dimensions have to be compatible with the original Dimensions`

In [ ]:
x.shape

torch.Size([9])

In [ ]:
# Adding an extra dimension
x_reshaped_1 = x.reshape(1, 9)
x_reshaped_1

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

- We added an extra dimension (extra square bracket)

In [ ]:
x_reshaped_2 = x.reshape(1, 7)
x_reshaped_2

RuntimeError: ignored

- Error because we're trying to squeeze 9 elements into 7 elements

In [ ]:
x_reshaped_3 = x.reshape(2, 9)
x_reshaped_3

RuntimeError: ignored

- Error because we're trying to double the amount of elements

In [ ]:
x_reshaped_4 = x.reshape(9, 1)
x_reshaped_4

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [ ]:
x_reshaped_5 = x.reshape(3, 3)
x_reshaped_5

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

- Compatible because 3x3=9

## 2. Changing View

- view shares memory with original tensor
- Changing z, changes x

In [ ]:
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
z = x.view(9,1)
z

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [ ]:
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
z[0] = 5

In [ ]:
z, x

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

- In both the 0-th element is changed to 5

## 3. Stacking

In [ ]:
x

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_stacked_A = torch.stack([x, x, x, x, x], dim=0)
x_stacked_A

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_stacked_B = torch.stack([x, x, x, x, x], dim=1)
x_stacked_B

tensor([[5., 5., 5., 5., 5.],
        [2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8.],
        [9., 9., 9., 9., 9.]])

- We can also use `hstack` and `vstack`

## 4. Squeeze

- `torch.squeeze():` removes all single dimensions from a target tensor

In [ ]:
x, x_reshaped_1

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [ ]:
x_squeezed = x_reshaped_1.squeeze()
x_squeezed

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

## 5. Unsqueeze

- `torch.unsqueeze():` adds a single dimension to a target tensor at a specific dimension

In [ ]:
x_squeezed, x_squeezed.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# adding an extra dimension at the 0-th dimension
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed, x_unsqueezed.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# adding an extra dimension at the 1st dimension
x_unsqueezed_2 = x_squeezed.unsqueeze(dim=1)
x_unsqueezed_2, x_unsqueezed_2.shape

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

## 6. Permute

- `torch.permute(input=, dim=):` Rearranges the axis/dimensions of the target tensor in a specified order
- returns a view of the original tensor with its dimensions permuted

In [ ]:
t1 = torch.rand(size=(5,2,9))
t1

tensor([[[0.6515, 0.2274, 0.3356, 0.4171, 0.0354, 0.6738, 0.7904, 0.3733,
          0.4684],
         [0.6542, 0.4399, 0.4337, 0.3150, 0.4731, 0.9535, 0.3958, 0.8972,
          0.8491]],

        [[0.1202, 0.8249, 0.4088, 0.4795, 0.6425, 0.1979, 0.2411, 0.9310,
          0.6374],
         [0.4056, 0.8762, 0.8305, 0.7741, 0.2256, 0.9365, 0.4430, 0.8867,
          0.5860]],

        [[0.9171, 0.4463, 0.2724, 0.5061, 0.7899, 0.1533, 0.4188, 0.3301,
          0.6202],
         [0.8684, 0.8084, 0.4382, 0.1782, 0.3123, 0.2006, 0.7863, 0.6236,
          0.4582]],

        [[0.1697, 0.6600, 0.6038, 0.3019, 0.7754, 0.0628, 0.5239, 0.1597,
          0.6056],
         [0.5405, 0.6859, 0.2266, 0.2277, 0.5608, 0.7725, 0.1534, 0.6680,
          0.2959]],

        [[0.1579, 0.6511, 0.7119, 0.5363, 0.0904, 0.7068, 0.3318, 0.0832,
          0.3205],
         [0.3202, 0.1533, 0.4695, 0.7486, 0.1387, 0.8395, 0.9427, 0.6273,
          0.6362]]])

In [ ]:
t1.size()

torch.Size([5, 2, 9])

In [ ]:
t1.permute(2, 0, 1).size(), t1.permute(2, 0, 1)

(torch.Size([9, 5, 2]),
 tensor([[[0.6515, 0.6542],
          [0.1202, 0.4056],
          [0.9171, 0.8684],
          [0.1697, 0.5405],
          [0.1579, 0.3202]],
 
         [[0.2274, 0.4399],
          [0.8249, 0.8762],
          [0.4463, 0.8084],
          [0.6600, 0.6859],
          [0.6511, 0.1533]],
 
         [[0.3356, 0.4337],
          [0.4088, 0.8305],
          [0.2724, 0.4382],
          [0.6038, 0.2266],
          [0.7119, 0.4695]],
 
         [[0.4171, 0.3150],
          [0.4795, 0.7741],
          [0.5061, 0.1782],
          [0.3019, 0.2277],
          [0.5363, 0.7486]],
 
         [[0.0354, 0.4731],
          [0.6425, 0.2256],
          [0.7899, 0.3123],
          [0.7754, 0.5608],
          [0.0904, 0.1387]],
 
         [[0.6738, 0.9535],
          [0.1979, 0.9365],
          [0.1533, 0.2006],
          [0.0628, 0.7725],
          [0.7068, 0.8395]],
 
         [[0.7904, 0.3958],
          [0.2411, 0.4430],
          [0.4188, 0.7863],
          [0.5239, 0.1534],
      