In [ ]:
# Load the Drive helper and mount
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Lesson 29 - Indexing (selecting data from tensors)

- Indexing in PyTorch is similar to indexing in Numpy

In [ ]:
x = torch.arange(1, 10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x = x.reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

## Indexing on the Tensor

In [ ]:
# Indexing on the 0-th Dimension / The first bracket
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Indexing on the 1st Dimension / The 2nd bracket
x[0][0], x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [ ]:
# Indexing on the 2nd Dimension / The 3rd bracket
x[0][0][0], x[0,0,0]

(tensor(1), tensor(1))

In [ ]:
x[0][0][2]

tensor(3)

In [ ]:
x[1][1][1]

IndexError: ignored

- Error because there's only 1 dimension in the 0th index

In [ ]:
x[0][1][1]

tensor(5)

### Challenge: Get number 9

In [ ]:
x[0][2][2]

tensor(9)

## Using `:` in tensor indexing

- We can use `:` to select all of the target dimension `(will have to use , notation)`

In [ ]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
x[:, 1]

tensor([[4, 5, 6]])

In [ ]:
x[:, :, :]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[:, :, 0]

tensor([[1, 4, 7]])

In [ ]:
# Get all values of the 0th and 1st dimension, but only index 1 out of the 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
x[:, :, 2]

tensor([[3, 6, 9]])

In [ ]:
# Get all values of the 0th dimension but only the 1 index value of the 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of the 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

- This is equivilent to `x[0][0]`

### Index on x to return 3, 6, 9

In [ ]:
x[:, :, 2]

tensor([[3, 6, 9]])