In [ ]:
# Load the Drive helper and mount
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Lesson 21 - Manipulating Tensors (Tensor Operations)

Tensor Operations include:
1. Addition
2. Subraction
3. Multiplication - element wise
4. Division
5. Matrix Multiplication (dot product)

In [ ]:
tensor_1 = torch.tensor([1,2,3])
tensor_1

tensor([1, 2, 3])

In [ ]:
# Addition (2 methods)
tensor_1 + 100 , torch.add(tensor_1, 100)

(tensor([101, 102, 103]), tensor([101, 102, 103]))

In [ ]:
# Subraction
tensor_1 - 100

tensor([-99, -98, -97])

In [ ]:
# Element wise Multiplication (2 methods)
tensor_1 * 30 , torch.mul(tensor_1, 30)

(tensor([30, 60, 90]), tensor([30, 60, 90]))

# Lesson 22+23 - Matrix Multiplication (dot product)

- In Matrix Multiplication - every row multiplies with every column
- `torch.mm` is short for `torch.matmul`, we can use `@` also

## Vector dot product

In [ ]:
tensor_a = torch.tensor([5,7,20])
tensor_b = torch.tensor([3,5,8])

In [ ]:
print(tensor_a, "*", tensor_b)
print(f"Equals: {tensor_a * tensor_b}")

tensor([ 5,  7, 20]) * tensor([3, 5, 8])
Equals: tensor([ 15,  35, 160])


In [ ]:
# 2nd method
torch.matmul(tensor_a, tensor_b) # faster method

tensor(210)

## Matrix dot product

In [ ]:
torch.matmul(torch.rand(3,4), torch.rand(4,3)) # The inner dimensions must match
# The resulting matrix has shape of outer dimensions

tensor([[0.8295, 0.6812, 0.9878],
        [1.1610, 0.7766, 1.1530],
        [1.1087, 1.4161, 1.5723]])

# Lesson 24 - Transposing a Tensor

- A Matrix can be transposed in order to avoid dimension errors in multiplication.

In [ ]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

In [ ]:
torch.mm(tensor_A, tensor_B)

RuntimeError: ignored

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
# Transpose
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])